// Generated from forexfactory.com/calendar via cloudscraper on 2026-05-06.
// Range: 2026-04-21 .. 2026-05-21 (15 days before and after 2026-05-06).
// Do NOT hand-edit; rerun scripts/scrape_econ_calendar.py to refresh.

use super::{EconomicEvent, Impact};

pub const EVENTS: &[EconomicEvent] = &[
    EconomicEvent { date: "2026-04-21", time: "10:45pm", currency: "AUD", impact: Impact::Low, title: "RBA Assist Gov Hunter Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-21", time: "11:00pm", currency: "GBP", impact: Impact::High, title: "CPI y/y", actual: "3.3%", forecast: "3.3%", previous: "3.0%" },
    EconomicEvent { date: "2026-04-21", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Core CPI y/y", actual: "3.1%", forecast: "3.2%", previous: "3.2%" },
    EconomicEvent { date: "2026-04-21", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "PPI Input m/m", actual: "4.4%", forecast: "2.9%", previous: "0.9%" },
    EconomicEvent { date: "2026-04-21", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "PPI Output m/m", actual: "0.9%", forecast: "1.0%", previous: "-0.5%" },
    EconomicEvent { date: "2026-04-21", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "RPI y/y", actual: "4.1%", forecast: "3.9%", previous: "3.6%" },
    EconomicEvent { date: "2026-04-21", time: "11:30am", currency: "USD", impact: Impact::Low, title: "FOMC Member Waller Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-21", time: "1:30pm", currency: "USD", impact: Impact::Low, title: "API Weekly Statistical Bulletin", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-21", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "German ZEW Economic Sentiment", actual: "-17.2", forecast: "-5.9", previous: "-0.5" },
    EconomicEvent { date: "2026-04-21", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "ZEW Economic Sentiment", actual: "-20.4", forecast: "-12.7", previous: "-8.5" },
    EconomicEvent { date: "2026-04-21", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Trade Balance", actual: "0.09T", forecast: "0.23T", previous: "-0.37T" },
    EconomicEvent { date: "2026-04-21", time: "5:15am", currency: "USD", impact: Impact::Low, title: "ADP Weekly Employment Change", actual: "54.8K", forecast: "", previous: "40.3K" },
    EconomicEvent { date: "2026-04-21", time: "5:30am", currency: "USD", impact: Impact::High, title: "Core Retail Sales m/m", actual: "1.9%", forecast: "1.4%", previous: "0.7%" },
    EconomicEvent { date: "2026-04-21", time: "5:30am", currency: "USD", impact: Impact::High, title: "Retail Sales m/m", actual: "1.7%", forecast: "1.4%", previous: "0.7%" },
    EconomicEvent { date: "2026-04-21", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "President Trump Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-21", time: "5:30pm", currency: "AUD", impact: Impact::Low, title: "MI Leading Index m/m", actual: "-0.1%", forecast: "", previous: "-0.1%" },
    EconomicEvent { date: "2026-04-21", time: "7:00am", currency: "USD", impact: Impact::High, title: "Fed Chairman-Designate Warsh Testifies", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-21", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "Pending Home Sales m/m", actual: "1.5%", forecast: "0.0%", previous: "2.5%" },
    EconomicEvent { date: "2026-04-21", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Business Inventories m/m", actual: "0.4%", forecast: "0.4%", previous: "0.0%" },
    EconomicEvent { date: "2026-04-21", time: "8:28am", currency: "NZD", impact: Impact::Low, title: "GDT Price Index", actual: "-2.7%", forecast: "", previous: "-3.4%" },
    EconomicEvent { date: "2026-04-21", time: "9:15am", currency: "CHF", impact: Impact::Low, title: "Gov Board Member Tschudin Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-22", time: "10:00am", currency: "EUR", impact: Impact::Low, title: "German Buba President Nagel Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-22", time: "10:30am", currency: "EUR", impact: Impact::Medium, title: "ECB President Lagarde Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-22", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Public Sector Net Borrowing", actual: "12.6B", forecast: "10.4B", previous: "12.8B" },
    EconomicEvent { date: "2026-04-22", time: "1:05am", currency: "GBP", impact: Impact::Low, title: "MPC Member Breeden Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-22", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "HPI y/y", actual: "1.2%", forecast: "0.9%", previous: "1.0%" },
    EconomicEvent { date: "2026-04-22", time: "3:00am", currency: "EUR", impact: Impact::Low, title: "German Buba Monthly Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-22", time: "4:00pm", currency: "AUD", impact: Impact::Low, title: "Flash Manufacturing PMI", actual: "51.0", forecast: "", previous: "49.8" },
    EconomicEvent { date: "2026-04-22", time: "4:00pm", currency: "AUD", impact: Impact::Low, title: "Flash Services PMI", actual: "50.3", forecast: "", previous: "46.3" },
    EconomicEvent { date: "2026-04-22", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "NHPI m/m", actual: "-0.2%", forecast: "0.2%", previous: "0.3%" },
    EconomicEvent { date: "2026-04-22", time: "5:30pm", currency: "JPY", impact: Impact::Low, title: "Flash Manufacturing PMI", actual: "54.9", forecast: "51.1", previous: "51.6" },
    EconomicEvent { date: "2026-04-22", time: "7:00am", currency: "EUR", impact: Impact::Low, title: "Consumer Confidence", actual: "-21", forecast: "-18", previous: "-16" },
    EconomicEvent { date: "2026-04-22", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Crude Oil Inventories", actual: "1.9M", forecast: "-1.9M", previous: "-0.9M" },
    EconomicEvent { date: "2026-04-22", time: "8:00pm", currency: "NZD", impact: Impact::Low, title: "Credit Card Spending y/y", actual: "2.1%", forecast: "", previous: "1.1%" },
    EconomicEvent { date: "2026-04-23", time: "11:00pm", currency: "GBP", impact: Impact::High, title: "Retail Sales m/m", actual: "0.7%", forecast: "0.0%", previous: "-0.6%" },
    EconomicEvent { date: "2026-04-23", time: "12:15am", currency: "EUR", impact: Impact::Medium, title: "French Flash Manufacturing PMI", actual: "52.8", forecast: "49.5", previous: "50.0" },
    EconomicEvent { date: "2026-04-23", time: "12:15am", currency: "EUR", impact: Impact::Medium, title: "French Flash Services PMI", actual: "46.5", forecast: "48.5", previous: "48.8" },
    EconomicEvent { date: "2026-04-23", time: "12:30am", currency: "EUR", impact: Impact::High, title: "German Flash Manufacturing PMI", actual: "51.2", forecast: "51.4", previous: "52.2" },
    EconomicEvent { date: "2026-04-23", time: "12:30am", currency: "EUR", impact: Impact::High, title: "German Flash Services PMI", actual: "46.9", forecast: "50.4", previous: "50.9" },
    EconomicEvent { date: "2026-04-23", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Flash Manufacturing PMI", actual: "52.2", forecast: "50.9", previous: "51.6" },
    EconomicEvent { date: "2026-04-23", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Flash Services PMI", actual: "47.4", forecast: "49.8", previous: "50.2" },
    EconomicEvent { date: "2026-04-23", time: "1:30am", currency: "GBP", impact: Impact::High, title: "Flash Manufacturing PMI", actual: "53.6", forecast: "50.3", previous: "51.0" },
    EconomicEvent { date: "2026-04-23", time: "1:30am", currency: "GBP", impact: Impact::High, title: "Flash Services PMI", actual: "52.0", forecast: "50.0", previous: "50.5" },
    EconomicEvent { date: "2026-04-23", time: "3:00am", currency: "GBP", impact: Impact::Low, title: "CBI Industrial Order Expectations", actual: "-38", forecast: "-34", previous: "-27" },
    EconomicEvent { date: "2026-04-23", time: "4:30pm", currency: "JPY", impact: Impact::Low, title: "National Core CPI y/y", actual: "1.8%", forecast: "1.7%", previous: "1.6%" },
    EconomicEvent { date: "2026-04-23", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "SPPI y/y", actual: "3.1%", forecast: "3.0%", previous: "2.7%" },
    EconomicEvent { date: "2026-04-23", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "IPPI m/m", actual: "2.4%", forecast: "1.6%", previous: "0.6%" },
    EconomicEvent { date: "2026-04-23", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "RMPI m/m", actual: "12.0%", forecast: "9.3%", previous: "0.9%" },
    EconomicEvent { date: "2026-04-23", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Unemployment Claims", actual: "214K", forecast: "211K", previous: "208K" },
    EconomicEvent { date: "2026-04-23", time: "6:21am", currency: "GBP", impact: Impact::Low, title: "GfK Consumer Confidence", actual: "-25", forecast: "-24", previous: "-21" },
    EconomicEvent { date: "2026-04-23", time: "6:45am", currency: "USD", impact: Impact::Medium, title: "Flash Manufacturing PMI", actual: "54.0", forecast: "52.5", previous: "52.3" },
    EconomicEvent { date: "2026-04-23", time: "6:45am", currency: "USD", impact: Impact::Medium, title: "Flash Services PMI", actual: "51.3", forecast: "50.5", previous: "49.8" },
    EconomicEvent { date: "2026-04-23", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Natural Gas Storage", actual: "103B", forecast: "96B", previous: "59B" },
    EconomicEvent { date: "2026-04-23", time: "8:00am", currency: "EUR", impact: Impact::Low, title: "German Buba President Nagel Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-24", time: "1:00am", currency: "CHF", impact: Impact::Medium, title: "SNB Chairman Schlegel Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-24", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "German ifo Business Climate", actual: "84.4", forecast: "85.7", previous: "86.3" },
    EconomicEvent { date: "2026-04-24", time: "2:01am", currency: "CNY", impact: Impact::Low, title: "Foreign Direct Investment ytd/y", actual: "-7.3%", forecast: "", previous: "-5.7%" },
    EconomicEvent { date: "2026-04-24", time: "5:30am", currency: "CAD", impact: Impact::Medium, title: "Core Retail Sales m/m", actual: "0.5%", forecast: "0.8%", previous: "1.0%" },
    EconomicEvent { date: "2026-04-24", time: "5:30am", currency: "CAD", impact: Impact::Medium, title: "Retail Sales m/m", actual: "0.7%", forecast: "0.9%", previous: "1.2%" },
    EconomicEvent { date: "2026-04-24", time: "5:32am", currency: "EUR", impact: Impact::Low, title: "Belgian NBB Business Climate", actual: "-14.2", forecast: "-14.8", previous: "-13.7" },
    EconomicEvent { date: "2026-04-24", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "Revised UoM Consumer Sentiment", actual: "49.8", forecast: "48.5", previous: "47.6" },
    EconomicEvent { date: "2026-04-24", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Revised UoM Inflation Expectations", actual: "4.7%", forecast: "", previous: "4.8%" },
    EconomicEvent { date: "2026-04-25", time: "7:45pm", currency: "USD", impact: Impact::Medium, title: "President Trump Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-25", time: "9:00am", currency: "USD", impact: Impact::Medium, title: "President Trump Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-26", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German GfK Consumer Climate", actual: "-33.3", forecast: "-30.2", previous: "-28.1" },
    EconomicEvent { date: "2026-04-26", time: "4:00pm", currency: "USD", impact: Impact::Medium, title: "President Trump Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-26", time: "All Day", currency: "NZD", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-26", time: "All Day", currency: "AUD", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-27", time: "10:00pm", currency: "JPY", impact: Impact::Low, title: "BOJ Core CPI y/y", actual: "1.7%", forecast: "1.9%", previous: "1.7%" },
    EconomicEvent { date: "2026-04-27", time: "11:30pm", currency: "JPY", impact: Impact::High, title: "BOJ Press Conference", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-27", time: "3:00am", currency: "GBP", impact: Impact::Low, title: "CBI Realized Sales", actual: "-68", forecast: "-42", previous: "-52" },
    EconomicEvent { date: "2026-04-27", time: "4:01pm", currency: "GBP", impact: Impact::Low, title: "BRC Shop Price Index y/y", actual: "1.0%", forecast: "1.4%", previous: "1.2%" },
    EconomicEvent { date: "2026-04-27", time: "4:30pm", currency: "JPY", impact: Impact::Low, title: "Unemployment Rate", actual: "2.7%", forecast: "2.6%", previous: "2.6%" },
    EconomicEvent { date: "2026-04-27", time: "6:00am", currency: "CNY", impact: Impact::Low, title: "CB Leading Index m/m", actual: "-0.2%", forecast: "", previous: "-0.2%" },
    EconomicEvent { date: "2026-04-27", time: "8:04pm", currency: "JPY", impact: Impact::High, title: "BOJ Outlook Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-27", time: "8:04pm", currency: "JPY", impact: Impact::High, title: "BOJ Policy Rate", actual: "<0.75%", forecast: "<0.75%", previous: "<0.75%" },
    EconomicEvent { date: "2026-04-27", time: "8:04pm", currency: "JPY", impact: Impact::High, title: "Monetary Policy Statement", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-28", time: "12:00am", currency: "EUR", impact: Impact::Low, title: "Spanish Unemployment Rate", actual: "10.8%", forecast: "9.8%", previous: "9.9%" },
    EconomicEvent { date: "2026-04-28", time: "1:30pm", currency: "USD", impact: Impact::Low, title: "API Weekly Statistical Bulletin", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-28", time: "5:15am", currency: "USD", impact: Impact::Low, title: "ADP Weekly Employment Change", actual: "39.3K", forecast: "", previous: "40.3K" },
    EconomicEvent { date: "2026-04-28", time: "5:30pm", currency: "NZD", impact: Impact::Medium, title: "RBNZ Gov Breman Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-28", time: "6:00am", currency: "USD", impact: Impact::Low, title: "HPI m/m", actual: "0.0%", forecast: "0.1%", previous: "0.2%" },
    EconomicEvent { date: "2026-04-28", time: "6:00am", currency: "USD", impact: Impact::Low, title: "S&P/CS Composite-20 HPI y/y", actual: "0.9%", forecast: "1.1%", previous: "1.2%" },
    EconomicEvent { date: "2026-04-28", time: "6:30pm", currency: "AUD", impact: Impact::High, title: "CPI m/m", actual: "1.1%", forecast: "1.3%", previous: "0.0%" },
    EconomicEvent { date: "2026-04-28", time: "6:30pm", currency: "AUD", impact: Impact::High, title: "CPI y/y", actual: "4.6%", forecast: "4.8%", previous: "3.7%" },
    EconomicEvent { date: "2026-04-28", time: "6:30pm", currency: "AUD", impact: Impact::High, title: "Trimmed Mean CPI m/m", actual: "0.3%", forecast: "0.3%", previous: "0.2%" },
    EconomicEvent { date: "2026-04-28", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "CB Consumer Confidence", actual: "92.8", forecast: "89.0", previous: "92.2" },
    EconomicEvent { date: "2026-04-28", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Richmond Manufacturing Index", actual: "3", forecast: "2", previous: "0" },
    EconomicEvent { date: "2026-04-28", time: "All Day", currency: "JPY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-28", time: "All Day", currency: "EUR", impact: Impact::Medium, title: "German Prelim CPI m/m", actual: "0.6%", forecast: "0.7%", previous: "1.1%" },
    EconomicEvent { date: "2026-04-29", time: "10:00pm", currency: "JPY", impact: Impact::Low, title: "Consumer Confidence", actual: "32.2", forecast: "32.8", previous: "33.3" },
    EconomicEvent { date: "2026-04-29", time: "10:00pm", currency: "JPY", impact: Impact::Low, title: "Housing Starts y/y", actual: "-29.3%", forecast: "-28.7%", previous: "-4.9%" },
    EconomicEvent { date: "2026-04-29", time: "10:30pm", currency: "EUR", impact: Impact::Low, title: "French Consumer Spending m/m", actual: "0.7%", forecast: "0.7%", previous: "-1.4%" },
    EconomicEvent { date: "2026-04-29", time: "10:30pm", currency: "EUR", impact: Impact::Low, title: "French Flash GDP q/q", actual: "0.0%", forecast: "0.2%", previous: "0.2%" },
    EconomicEvent { date: "2026-04-29", time: "11:00am", currency: "USD", impact: Impact::High, title: "Federal Funds Rate", actual: "3.75%", forecast: "3.75%", previous: "3.75%" },
    EconomicEvent { date: "2026-04-29", time: "11:00am", currency: "USD", impact: Impact::High, title: "FOMC Statement", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-29", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German Import Prices m/m", actual: "3.6%", forecast: "3.6%", previous: "0.3%" },
    EconomicEvent { date: "2026-04-29", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German Retail Sales m/m", actual: "-2.0%", forecast: "-0.3%", previous: "-0.3%" },
    EconomicEvent { date: "2026-04-29", time: "11:30am", currency: "USD", impact: Impact::High, title: "FOMC Press Conference", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-29", time: "11:45pm", currency: "EUR", impact: Impact::Low, title: "French Prelim CPI m/m", actual: "1.0%", forecast: "0.9%", previous: "1.0%" },
    EconomicEvent { date: "2026-04-29", time: "11:45pm", currency: "EUR", impact: Impact::Low, title: "French Prelim Private Payrolls q/q", actual: "-0.1%", forecast: "-0.1%", previous: "-0.1%" },
    EconomicEvent { date: "2026-04-29", time: "12:00am", currency: "EUR", impact: Impact::Low, title: "Spanish Flash CPI y/y", actual: "3.2%", forecast: "3.5%", previous: "3.3%" },
    EconomicEvent { date: "2026-04-29", time: "1:00am", currency: "CHF", impact: Impact::Low, title: "UBS Economic Expectations", actual: "-30.3", forecast: "", previous: "-35.0" },
    EconomicEvent { date: "2026-04-29", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "M3 Money Supply y/y", actual: "3.2%", forecast: "3.1%", previous: "3.0%" },
    EconomicEvent { date: "2026-04-29", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Private Loans y/y", actual: "3.0%", forecast: "3.1%", previous: "3.0%" },
    EconomicEvent { date: "2026-04-29", time: "2:17am", currency: "EUR", impact: Impact::Low, title: "Italian 10-y Bond Auction", actual: "3.77|1.7", forecast: "", previous: "4.09|1.7" },
    EconomicEvent { date: "2026-04-29", time: "2:32am", currency: "EUR", impact: Impact::Low, title: "German 10-y Bond Auction", actual: "3.08|1.5", forecast: "", previous: "2.92|1.2" },
    EconomicEvent { date: "2026-04-29", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Prelim Industrial Production m/m", actual: "-0.5%", forecast: "1.0%", previous: "-2.0%" },
    EconomicEvent { date: "2026-04-29", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Retail Sales y/y", actual: "1.7%", forecast: "0.9%", previous: "-0.1%" },
    EconomicEvent { date: "2026-04-29", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Building Permits", actual: "1.37M", forecast: "1.39M", previous: "1.54M" },
    EconomicEvent { date: "2026-04-29", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Core Durable Goods Orders m/m", actual: "0.9%", forecast: "0.4%", previous: "0.9%" },
    EconomicEvent { date: "2026-04-29", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Durable Goods Orders m/m", actual: "0.8%", forecast: "0.4%", previous: "-1.3%" },
    EconomicEvent { date: "2026-04-29", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Goods Trade Balance", actual: "-87.9B", forecast: "-87.5B", previous: "-83.5B" },
    EconomicEvent { date: "2026-04-29", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Housing Starts", actual: "1.50M", forecast: "1.38M", previous: "1.36M" },
    EconomicEvent { date: "2026-04-29", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Prelim Wholesale Inventories m/m", actual: "1.4%", forecast: "0.4%", previous: "0.9%" },
    EconomicEvent { date: "2026-04-29", time: "6:00pm", currency: "NZD", impact: Impact::Low, title: "ANZ Business Confidence", actual: "-10.6", forecast: "", previous: "32.5" },
    EconomicEvent { date: "2026-04-29", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "Import Prices q/q", actual: "0.1%", forecast: "0.4%", previous: "0.9%" },
    EconomicEvent { date: "2026-04-29", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "Private Sector Credit m/m", actual: "0.7%", forecast: "0.6%", previous: "0.6%" },
    EconomicEvent { date: "2026-04-29", time: "6:30pm", currency: "CNY", impact: Impact::Low, title: "Manufacturing PMI", actual: "50.3", forecast: "50.1", previous: "50.4" },
    EconomicEvent { date: "2026-04-29", time: "6:30pm", currency: "CNY", impact: Impact::Low, title: "Non-Manufacturing PMI", actual: "49.4", forecast: "49.9", previous: "50.1" },
    EconomicEvent { date: "2026-04-29", time: "6:45am", currency: "CAD", impact: Impact::High, title: "BOC Monetary Policy Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-29", time: "6:45am", currency: "CAD", impact: Impact::High, title: "BOC Rate Statement", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-29", time: "6:45am", currency: "CAD", impact: Impact::High, title: "Overnight Rate", actual: "2.25%", forecast: "2.25%", previous: "2.25%" },
    EconomicEvent { date: "2026-04-29", time: "6:45pm", currency: "CNY", impact: Impact::Low, title: "RatingDog Manufacturing PMI", actual: "52.2", forecast: "50.9", previous: "50.8" },
    EconomicEvent { date: "2026-04-29", time: "7:30am", currency: "CAD", impact: Impact::High, title: "BOC Press Conference", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-29", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Crude Oil Inventories", actual: "-6.2M", forecast: "0.3M", previous: "1.9M" },
    EconomicEvent { date: "2026-04-29", time: "Feb Data", currency: "USD", impact: Impact::Low, title: "Building Permits", actual: "1.54M", forecast: "", previous: "1.39M" },
    EconomicEvent { date: "2026-04-29", time: "Feb Data", currency: "USD", impact: Impact::Low, title: "Housing Starts", actual: "1.36M", forecast: "", previous: "1.40M" },
    EconomicEvent { date: "2026-04-30", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Nationwide HPI m/m", actual: "0.4%", forecast: "-0.3%", previous: "0.9%" },
    EconomicEvent { date: "2026-04-30", time: "11:30pm", currency: "AUD", impact: Impact::Low, title: "Commodity Prices y/y", actual: "15.7%", forecast: "", previous: "12.6%" },
    EconomicEvent { date: "2026-04-30", time: "11:30pm", currency: "CHF", impact: Impact::Low, title: "Retail Sales y/y", actual: "0.5%", forecast: "0.6%", previous: "0.4%" },
    EconomicEvent { date: "2026-04-30", time: "12:00am", currency: "CHF", impact: Impact::Low, title: "KOF Economic Barometer", actual: "97.9", forecast: "95.8", previous: "95.6" },
    EconomicEvent { date: "2026-04-30", time: "12:00am", currency: "EUR", impact: Impact::Low, title: "Spanish Flash GDP q/q", actual: "0.6%", forecast: "0.5%", previous: "0.8%" },
    EconomicEvent { date: "2026-04-30", time: "12:55am", currency: "EUR", impact: Impact::Low, title: "German Unemployment Change", actual: "20K", forecast: "4K", previous: "3K" },
    EconomicEvent { date: "2026-04-30", time: "1:00am", currency: "EUR", impact: Impact::Medium, title: "German Prelim GDP q/q", actual: "0.3%", forecast: "0.1%", previous: "0.3%" },
    EconomicEvent { date: "2026-04-30", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Italian Prelim GDP q/q", actual: "0.2%", forecast: "0.1%", previous: "0.3%" },
    EconomicEvent { date: "2026-04-30", time: "1:30am", currency: "EUR", impact: Impact::Low, title: "Italian Monthly Unemployment Rate", actual: "5.2%", forecast: "5.3%", previous: "5.4%" },
    EconomicEvent { date: "2026-04-30", time: "2:00am", currency: "EUR", impact: Impact::Medium, title: "Core CPI Flash Estimate y/y", actual: "2.2%", forecast: "2.2%", previous: "2.3%" },
    EconomicEvent { date: "2026-04-30", time: "2:00am", currency: "EUR", impact: Impact::Medium, title: "CPI Flash Estimate y/y", actual: "3.0%", forecast: "3.0%", previous: "2.6%" },
    EconomicEvent { date: "2026-04-30", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Italian Prelim CPI m/m", actual: "1.2%", forecast: "0.9%", previous: "0.5%" },
    EconomicEvent { date: "2026-04-30", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Prelim Flash GDP q/q", actual: "0.1%", forecast: "0.2%", previous: "0.2%" },
    EconomicEvent { date: "2026-04-30", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Unemployment Rate", actual: "6.2%", forecast: "6.2%", previous: "6.3%" },
    EconomicEvent { date: "2026-04-30", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "Building Consents m/m", actual: "-1.3%", forecast: "", previous: "2.8%" },
    EconomicEvent { date: "2026-04-30", time: "4:00am", currency: "GBP", impact: Impact::High, title: "BOE Monetary Policy Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "4:00am", currency: "GBP", impact: Impact::High, title: "Monetary Policy Summary", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "4:00am", currency: "GBP", impact: Impact::High, title: "MPC Official Bank Rate Votes", actual: "1-0-8", forecast: "1-0-8", previous: "0-0-9" },
    EconomicEvent { date: "2026-04-30", time: "4:00am", currency: "GBP", impact: Impact::High, title: "Official Bank Rate", actual: "3.75%", forecast: "3.75%", previous: "3.75%" },
    EconomicEvent { date: "2026-04-30", time: "4:00am", currency: "GBP", impact: Impact::Low, title: "BOE Inflation Letter", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "4:30am", currency: "GBP", impact: Impact::High, title: "BOE Gov Bailey Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "4:30pm", currency: "JPY", impact: Impact::Medium, title: "Tokyo Core CPI y/y", actual: "1.5%", forecast: "1.8%", previous: "1.7%" },
    EconomicEvent { date: "2026-04-30", time: "5:15am", currency: "EUR", impact: Impact::High, title: "Main Refinancing Rate", actual: "2.15%", forecast: "2.15%", previous: "2.15%" },
    EconomicEvent { date: "2026-04-30", time: "5:15am", currency: "EUR", impact: Impact::High, title: "Monetary Policy Statement", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "CAD", impact: Impact::High, title: "GDP m/m", actual: "0.2%", forecast: "0.2%", previous: "0.1%" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::High, title: "Advance GDP q/q", actual: "2.0%", forecast: "2.2%", previous: "0.5%" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::High, title: "Core PCE Price Index m/m", actual: "0.3%", forecast: "0.3%", previous: "0.4%" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::High, title: "Employment Cost Index q/q", actual: "0.9%", forecast: "0.8%", previous: "0.7%" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Advance GDP Price Index q/q", actual: "3.6%", forecast: "3.8%", previous: "3.7%" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Unemployment Claims", actual: "189K", forecast: "213K", previous: "215K" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Personal Income m/m", actual: "0.6%", forecast: "0.3%", previous: "0.0%" },
    EconomicEvent { date: "2026-04-30", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Personal Spending m/m", actual: "0.9%", forecast: "0.9%", previous: "0.6%" },
    EconomicEvent { date: "2026-04-30", time: "5:30pm", currency: "JPY", impact: Impact::Low, title: "Final Manufacturing PMI", actual: "55.1", forecast: "54.9", previous: "54.9" },
    EconomicEvent { date: "2026-04-30", time: "5:45am", currency: "EUR", impact: Impact::High, title: "ECB Press Conference", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "PPI q/q", actual: "0.4%", forecast: "0.9%", previous: "0.8%" },
    EconomicEvent { date: "2026-04-30", time: "6:45am", currency: "USD", impact: Impact::Low, title: "Chicago PMI", actual: "49.2", forecast: "54.8", previous: "52.8" },
    EconomicEvent { date: "2026-04-30", time: "7:00am", currency: "USD", impact: Impact::Low, title: "CB Leading Index m/m", actual: "-0.6%", forecast: "-0.2%", previous: "0.3%" },
    EconomicEvent { date: "2026-04-30", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Natural Gas Storage", actual: "79B", forecast: "83B", previous: "103B" },
    EconomicEvent { date: "2026-04-30", time: "All Day", currency: "CNY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "All Day", currency: "CHF", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "All Day", currency: "EUR", impact: Impact::Holiday, title: "French Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "All Day", currency: "EUR", impact: Impact::Holiday, title: "German Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "All Day", currency: "EUR", impact: Impact::Holiday, title: "Italian Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-04-30", time: "Feb Data", currency: "USD", impact: Impact::Low, title: "CB Leading Index m/m", actual: "0.3%", forecast: "", previous: "-0.1%" },
    EconomicEvent { date: "2026-05-01", time: "12:00pm", currency: "USD", impact: Impact::Medium, title: "President Trump Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-01", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "Final Manufacturing PMI", actual: "53.7", forecast: "53.3", previous: "53.6" },
    EconomicEvent { date: "2026-05-01", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "M4 Money Supply m/m", actual: "0.8%", forecast: "0.5%", previous: "0.7%" },
    EconomicEvent { date: "2026-05-01", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "Mortgage Approvals", actual: "64K", forecast: "60K", previous: "63K" },
    EconomicEvent { date: "2026-05-01", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "Net Lending to Individuals m/m", actual: "8.0B", forecast: "5.9B", previous: "7.2B" },
    EconomicEvent { date: "2026-05-01", time: "4:15am", currency: "GBP", impact: Impact::Low, title: "MPC Member Pill Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-01", time: "6:30am", currency: "CAD", impact: Impact::Low, title: "Manufacturing PMI", actual: "53.3", forecast: "", previous: "50.0" },
    EconomicEvent { date: "2026-05-01", time: "6:45am", currency: "USD", impact: Impact::Low, title: "Final Manufacturing PMI", actual: "54.5", forecast: "54.0", previous: "54.0" },
    EconomicEvent { date: "2026-05-01", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "ISM Manufacturing PMI", actual: "52.7", forecast: "53.1", previous: "52.7" },
    EconomicEvent { date: "2026-05-01", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "ISM Manufacturing Prices", actual: "84.6", forecast: "80.0", previous: "78.3" },
    EconomicEvent { date: "2026-05-01", time: "All Day", currency: "USD", impact: Impact::Low, title: "Wards Total Vehicle Sales", actual: "15.9M", forecast: "16.0M", previous: "16.3M" },
    EconomicEvent { date: "2026-05-03", time: "6:00pm", currency: "AUD", impact: Impact::Low, title: "MI Inflation Gauge m/m", actual: "0.6%", forecast: "", previous: "1.3%" },
    EconomicEvent { date: "2026-05-03", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "ANZ Job Advertisements m/m", actual: "-0.8%", forecast: "", previous: "-3.2%" },
    EconomicEvent { date: "2026-05-03", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "Building Approvals m/m", actual: "-10.5%", forecast: "-10.2%", previous: "31.0%" },
    EconomicEvent { date: "2026-05-03", time: "All Day", currency: "JPY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-03", time: "All Day", currency: "CNY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "10:05am", currency: "EUR", impact: Impact::Low, title: "German Buba President Nagel Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "10:30pm", currency: "AUD", impact: Impact::High, title: "RBA Press Conference", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "11:00am", currency: "USD", impact: Impact::Low, title: "Loan Officer Survey", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "11:30pm", currency: "CHF", impact: Impact::Medium, title: "CPI m/m", actual: "0.3%", forecast: "0.3%", previous: "0.2%" },
    EconomicEvent { date: "2026-05-04", time: "12:15am", currency: "EUR", impact: Impact::Low, title: "Spanish Manufacturing PMI", actual: "51.7", forecast: "49.5", previous: "48.7" },
    EconomicEvent { date: "2026-05-04", time: "12:30am", currency: "CHF", impact: Impact::Low, title: "Manufacturing PMI", actual: "54.5", forecast: "52.0", previous: "53.3" },
    EconomicEvent { date: "2026-05-04", time: "12:30pm", currency: "CAD", impact: Impact::Medium, title: "BOC Gov Macklem Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "12:45am", currency: "EUR", impact: Impact::Low, title: "Italian Manufacturing PMI", actual: "52.1", forecast: "51.6", previous: "51.3" },
    EconomicEvent { date: "2026-05-04", time: "12:50am", currency: "EUR", impact: Impact::Low, title: "French Final Manufacturing PMI", actual: "52.8", forecast: "52.8", previous: "52.8" },
    EconomicEvent { date: "2026-05-04", time: "12:55am", currency: "EUR", impact: Impact::Low, title: "German Final Manufacturing PMI", actual: "51.4", forecast: "51.2", previous: "51.2" },
    EconomicEvent { date: "2026-05-04", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Final Manufacturing PMI", actual: "52.2", forecast: "52.2", previous: "52.2" },
    EconomicEvent { date: "2026-05-04", time: "1:30am", currency: "EUR", impact: Impact::Low, title: "Sentix Investor Confidence", actual: "-16.4", forecast: "-20.9", previous: "-19.2" },
    EconomicEvent { date: "2026-05-04", time: "6:00pm", currency: "NZD", impact: Impact::Low, title: "ANZ Commodity Prices m/m", actual: "-0.8%", forecast: "", previous: "4.2%" },
    EconomicEvent { date: "2026-05-04", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "Household Spending m/m", actual: "1.6%", forecast: "1.8%", previous: "0.3%" },
    EconomicEvent { date: "2026-05-04", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Factory Orders m/m", actual: "1.5%", forecast: "0.5%", previous: "0.3%" },
    EconomicEvent { date: "2026-05-04", time: "9:30pm", currency: "AUD", impact: Impact::High, title: "Cash Rate", actual: "4.35%", forecast: "4.35%", previous: "4.10%" },
    EconomicEvent { date: "2026-05-04", time: "9:30pm", currency: "AUD", impact: Impact::High, title: "RBA Monetary Policy Statement", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "9:30pm", currency: "AUD", impact: Impact::High, title: "RBA Rate Statement", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "9:50am", currency: "USD", impact: Impact::Low, title: "FOMC Member Williams Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "All Day", currency: "GBP", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "All Day", currency: "EUR", impact: Impact::Low, title: "Eurogroup Meetings", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "All Day", currency: "JPY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-04", time: "All Day", currency: "CNY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "11:45pm", currency: "EUR", impact: Impact::Low, title: "French Industrial Production m/m", actual: "1.0%", forecast: "0.5%", previous: "-0.9%" },
    EconomicEvent { date: "2026-05-05", time: "12:00am", currency: "EUR", impact: Impact::Low, title: "Spanish Unemployment Change", actual: "-62.7K", forecast: "-18.6K", previous: "-22.9K" },
    EconomicEvent { date: "2026-05-05", time: "1:30pm", currency: "USD", impact: Impact::Low, title: "API Weekly Statistical Bulletin", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "2:00pm", currency: "NZD", impact: Impact::Low, title: "RBNZ Financial Stability Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "3:45pm", currency: "NZD", impact: Impact::High, title: "Employment Change q/q", actual: "0.2%", forecast: "0.3%", previous: "0.5%" },
    EconomicEvent { date: "2026-05-05", time: "3:45pm", currency: "NZD", impact: Impact::High, title: "Unemployment Rate", actual: "5.3%", forecast: "5.4%", previous: "5.4%" },
    EconomicEvent { date: "2026-05-05", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "Labor Cost Index q/q", actual: "0.5%", forecast: "0.4%", previous: "0.4%" },
    EconomicEvent { date: "2026-05-05", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "Trade Balance", actual: "1.8B", forecast: "-2.4B", previous: "-5.1B" },
    EconomicEvent { date: "2026-05-05", time: "5:30am", currency: "EUR", impact: Impact::Medium, title: "ECB President Lagarde Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Trade Balance", actual: "-60.3B", forecast: "-61.0B", previous: "-57.8B" },
    EconomicEvent { date: "2026-05-05", time: "6:00pm", currency: "NZD", impact: Impact::Medium, title: "RBNZ Gov Breman Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "6:31am", currency: "EUR", impact: Impact::Low, title: "French Gov Budget Balance", actual: "-42.9B", forecast: "", previous: "-32.1B" },
    EconomicEvent { date: "2026-05-05", time: "6:45am", currency: "USD", impact: Impact::Low, title: "Final Services PMI", actual: "51.0", forecast: "51.3", previous: "51.3" },
    EconomicEvent { date: "2026-05-05", time: "6:45pm", currency: "CNY", impact: Impact::Low, title: "RatingDog Services PMI", actual: "52.6", forecast: "52.0", previous: "52.1" },
    EconomicEvent { date: "2026-05-05", time: "7:00am", currency: "USD", impact: Impact::High, title: "ISM Services PMI", actual: "53.6", forecast: "53.7", previous: "54.0" },
    EconomicEvent { date: "2026-05-05", time: "7:00am", currency: "USD", impact: Impact::High, title: "JOLTS Job Openings", actual: "6.87M", forecast: "6.86M", previous: "6.92M" },
    EconomicEvent { date: "2026-05-05", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "New Home Sales", actual: "682K", forecast: "652K", previous: "635K" },
    EconomicEvent { date: "2026-05-05", time: "7:00am", currency: "USD", impact: Impact::Low, title: "FOMC Member Bowman Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "7:03am", currency: "USD", impact: Impact::Low, title: "RCM/TIPP Economic Optimism", actual: "42.6", forecast: "42.0", previous: "42.8" },
    EconomicEvent { date: "2026-05-05", time: "8:37am", currency: "NZD", impact: Impact::Low, title: "GDT Price Index", actual: "1.5%", forecast: "", previous: "-2.7%" },
    EconomicEvent { date: "2026-05-05", time: "9:30am", currency: "USD", impact: Impact::Low, title: "FOMC Member Barr Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "All Day", currency: "EUR", impact: Impact::Low, title: "ECOFIN Meetings", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "All Day", currency: "JPY", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-05", time: "Feb Data", currency: "USD", impact: Impact::Medium, title: "New Home Sales", actual: "635K", forecast: "", previous: "583K" },
    EconomicEvent { date: "2026-05-06", time: "10:00am", currency: "USD", impact: Impact::Low, title: "FOMC Member Goolsbee Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-06", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German Factory Orders m/m", actual: "", forecast: "1.0%", previous: "0.9%" },
    EconomicEvent { date: "2026-05-06", time: "11:45pm", currency: "EUR", impact: Impact::Low, title: "French Trade Balance", actual: "", forecast: "-6.7B", previous: "-5.8B" },
    EconomicEvent { date: "2026-05-06", time: "12:15am", currency: "EUR", impact: Impact::Low, title: "Spanish Services PMI", actual: "47.9", forecast: "51.9", previous: "53.3" },
    EconomicEvent { date: "2026-05-06", time: "12:45am", currency: "EUR", impact: Impact::Low, title: "Italian Services PMI", actual: "49.8", forecast: "47.9", previous: "48.8" },
    EconomicEvent { date: "2026-05-06", time: "12:50am", currency: "EUR", impact: Impact::Low, title: "French Final Services PMI", actual: "46.5", forecast: "46.5", previous: "46.5" },
    EconomicEvent { date: "2026-05-06", time: "12:55am", currency: "EUR", impact: Impact::Low, title: "German Final Services PMI", actual: "46.9", forecast: "46.9", previous: "46.9" },
    EconomicEvent { date: "2026-05-06", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Final Services PMI", actual: "47.6", forecast: "47.4", previous: "47.4" },
    EconomicEvent { date: "2026-05-06", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Italian Retail Sales m/m", actual: "0.8%", forecast: "-0.4%", previous: "-0.1%" },
    EconomicEvent { date: "2026-05-06", time: "1:15pm", currency: "CAD", impact: Impact::Medium, title: "BOC Gov Macklem Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-06", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "Final Services PMI", actual: "52.7", forecast: "51.9", previous: "52.0" },
    EconomicEvent { date: "2026-05-06", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "PPI m/m", actual: "3.4%", forecast: "3.3%", previous: "-0.6%" },
    EconomicEvent { date: "2026-05-06", time: "2:00am", currency: "USD", impact: Impact::Medium, title: "ADP Non-Farm Employment Change", actual: "", forecast: "118K", previous: "62K" },
    EconomicEvent { date: "2026-05-06", time: "2:10pm", currency: "NZD", impact: Impact::Medium, title: "RBNZ Gov Breman Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-06", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Monetary Base y/y", actual: "", forecast: "-10.5%", previous: "-11.6%" },
    EconomicEvent { date: "2026-05-06", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Monetary Policy Meeting Minutes", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-06", time: "6:30am", currency: "USD", impact: Impact::Low, title: "FOMC Member Musalem Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-06", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "Goods Trade Balance", actual: "", forecast: "4.38B", previous: "5.69B" },
    EconomicEvent { date: "2026-05-06", time: "7:00am", currency: "CAD", impact: Impact::Medium, title: "Ivey PMI", actual: "", forecast: "49.9", previous: "49.7" },
    EconomicEvent { date: "2026-05-06", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Crude Oil Inventories", actual: "", forecast: "-3.4M", previous: "-6.2M" },
    EconomicEvent { date: "2026-05-07", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German Industrial Production m/m", actual: "", forecast: "0.4%", previous: "-0.3%" },
    EconomicEvent { date: "2026-05-07", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German Trade Balance", actual: "", forecast: "17.8B", previous: "19.8B" },
    EconomicEvent { date: "2026-05-07", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Halifax HPI m/m", actual: "", forecast: "0.0%", previous: "-0.5%" },
    EconomicEvent { date: "2026-05-07", time: "11:05am", currency: "USD", impact: Impact::Low, title: "FOMC Member Hammack Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "12:00am", currency: "CHF", impact: Impact::Low, title: "Foreign Currency Reserves", actual: "", forecast: "", previous: "721B" },
    EconomicEvent { date: "2026-05-07", time: "12:00am", currency: "CHF", impact: Impact::Low, title: "Unemployment Rate", actual: "", forecast: "3.0%", previous: "3.0%" },
    EconomicEvent { date: "2026-05-07", time: "12:00pm", currency: "USD", impact: Impact::Low, title: "Consumer Credit m/m", actual: "", forecast: "12.5B", previous: "9.5B" },
    EconomicEvent { date: "2026-05-07", time: "12:30pm", currency: "USD", impact: Impact::Low, title: "FOMC Member Williams Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "1:00am", currency: "GBP", impact: Impact::Low, title: "MPC Member Lombardelli Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "Construction PMI", actual: "", forecast: "45.8", previous: "45.6" },
    EconomicEvent { date: "2026-05-07", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Retail Sales m/m", actual: "", forecast: "-0.3%", previous: "-0.2%" },
    EconomicEvent { date: "2026-05-07", time: "4:30am", currency: "USD", impact: Impact::Low, title: "Challenger Job Cuts y/y", actual: "", forecast: "", previous: "-78.0%" },
    EconomicEvent { date: "2026-05-07", time: "4:30pm", currency: "JPY", impact: Impact::Low, title: "Average Cash Earnings y/y", actual: "", forecast: "3.2%", previous: "3.4%" },
    EconomicEvent { date: "2026-05-07", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Unemployment Claims", actual: "", forecast: "205K", previous: "189K" },
    EconomicEvent { date: "2026-05-07", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Prelim Nonfarm Productivity q/q", actual: "", forecast: "0.7%", previous: "1.8%" },
    EconomicEvent { date: "2026-05-07", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Prelim Unit Labor Costs q/q", actual: "", forecast: "2.6%", previous: "4.4%" },
    EconomicEvent { date: "2026-05-07", time: "5:40am", currency: "GBP", impact: Impact::Low, title: "MPC Member Taylor Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Construction Spending m/m", actual: "", forecast: "0.3%", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Natural Gas Storage", actual: "", forecast: "72B", previous: "79B" },
    EconomicEvent { date: "2026-05-07", time: "All Day", currency: "EUR", impact: Impact::Holiday, title: "French Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "Feb Data", currency: "USD", impact: Impact::Low, title: "Construction Spending m/m", actual: "", forecast: "", previous: "-0.3%" },
    EconomicEvent { date: "2026-05-07", time: "Tentative", currency: "EUR", impact: Impact::Low, title: "Spanish 10-y Bond Auction", actual: "", forecast: "", previous: "3.44|2.0" },
    EconomicEvent { date: "2026-05-07", time: "Tentative", currency: "EUR", impact: Impact::Low, title: "French 10-y Bond Auction", actual: "", forecast: "", previous: "3.73|1.9" },
    EconomicEvent { date: "2026-05-07", time: "Tentative", currency: "USD", impact: Impact::Low, title: "FOMC Member Kashkari Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-07", time: "Tentative", currency: "CNY", impact: Impact::Low, title: "Trade Balance", actual: "", forecast: "575B", previous: "355B" },
    EconomicEvent { date: "2026-05-07", time: "Tentative", currency: "CNY", impact: Impact::Low, title: "USD-Denominated Trade Balance", actual: "", forecast: "83.1B", previous: "51.1B" },
    EconomicEvent { date: "2026-05-08", time: "12:00am", currency: "CHF", impact: Impact::Low, title: "SECO Consumer Climate", actual: "", forecast: "-46", previous: "-43" },
    EconomicEvent { date: "2026-05-08", time: "12:00am", currency: "EUR", impact: Impact::Medium, title: "ECB President Lagarde Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "2:45am", currency: "USD", impact: Impact::Low, title: "FOMC Member Cook Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "4:30pm", currency: "USD", impact: Impact::Low, title: "FOMC Member Bowman Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "4:30pm", currency: "USD", impact: Impact::Low, title: "FOMC Member Daly Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "4:30pm", currency: "USD", impact: Impact::Low, title: "FOMC Member Goolsbee Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "4:30pm", currency: "USD", impact: Impact::Low, title: "FOMC Member Waller Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "5:20am", currency: "GBP", impact: Impact::High, title: "BOE Gov Bailey Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-08", time: "5:30am", currency: "CAD", impact: Impact::High, title: "Employment Change", actual: "", forecast: "12.9K", previous: "14.1K" },
    EconomicEvent { date: "2026-05-08", time: "5:30am", currency: "CAD", impact: Impact::High, title: "Unemployment Rate", actual: "", forecast: "6.7%", previous: "6.7%" },
    EconomicEvent { date: "2026-05-08", time: "5:30am", currency: "USD", impact: Impact::High, title: "Average Hourly Earnings m/m", actual: "", forecast: "0.3%", previous: "0.2%" },
    EconomicEvent { date: "2026-05-08", time: "5:30am", currency: "USD", impact: Impact::High, title: "Non-Farm Employment Change", actual: "", forecast: "65K", previous: "178K" },
    EconomicEvent { date: "2026-05-08", time: "5:30am", currency: "USD", impact: Impact::High, title: "Unemployment Rate", actual: "", forecast: "4.3%", previous: "4.3%" },
    EconomicEvent { date: "2026-05-08", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "Prelim UoM Consumer Sentiment", actual: "", forecast: "49.7", previous: "49.8" },
    EconomicEvent { date: "2026-05-08", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "Prelim UoM Inflation Expectations", actual: "", forecast: "", previous: "4.7%" },
    EconomicEvent { date: "2026-05-08", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Final Wholesale Inventories m/m", actual: "", forecast: "1.4%", previous: "1.4%" },
    EconomicEvent { date: "2026-05-08", time: "9:15am", currency: "EUR", impact: Impact::Low, title: "German Buba President Nagel Speaks", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-10", time: "6:30pm", currency: "CNY", impact: Impact::Medium, title: "CPI y/y", actual: "", forecast: "", previous: "1.0%" },
    EconomicEvent { date: "2026-05-10", time: "6:30pm", currency: "CNY", impact: Impact::Medium, title: "PPI y/y", actual: "", forecast: "", previous: "0.5%" },
    EconomicEvent { date: "2026-05-11", time: "10:00pm", currency: "JPY", impact: Impact::Low, title: "Leading Indicators", actual: "", forecast: "", previous: "113.3%" },
    EconomicEvent { date: "2026-05-11", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German Final CPI m/m", actual: "", forecast: "", previous: "0.6%" },
    EconomicEvent { date: "2026-05-11", time: "11:30pm", currency: "CHF", impact: Impact::Low, title: "PPI m/m", actual: "", forecast: "", previous: "0.2%" },
    EconomicEvent { date: "2026-05-11", time: "12th-15th", currency: "EUR", impact: Impact::Low, title: "German WPI m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-11", time: "3:00am", currency: "EUR", impact: Impact::Low, title: "German Buba Monthly Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-11", time: "4:01pm", currency: "GBP", impact: Impact::Low, title: "BRC Retail Sales Monitor y/y", actual: "", forecast: "", previous: "3.1%" },
    EconomicEvent { date: "2026-05-11", time: "4:30pm", currency: "JPY", impact: Impact::Low, title: "Household Spending y/y", actual: "", forecast: "", previous: "-1.8%" },
    EconomicEvent { date: "2026-05-11", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "BOJ Summary of Opinions", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-11", time: "5:30pm", currency: "AUD", impact: Impact::Low, title: "Westpac Consumer Sentiment", actual: "", forecast: "", previous: "-12.5%" },
    EconomicEvent { date: "2026-05-11", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "NAB Business Confidence", actual: "", forecast: "", previous: "-29" },
    EconomicEvent { date: "2026-05-11", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Existing Home Sales", actual: "", forecast: "", previous: "3.98M" },
    EconomicEvent { date: "2026-05-11", time: "8:35pm", currency: "JPY", impact: Impact::Low, title: "10-y Bond Auction", actual: "", forecast: "", previous: "2.35|2.6" },
    EconomicEvent { date: "2026-05-11", time: "Tentative", currency: "USD", impact: Impact::High, title: "Fed Chair Nomination Vote", actual: "", forecast: "Pass", previous: "" },
    EconomicEvent { date: "2026-05-11", time: "Tentative", currency: "USD", impact: Impact::Low, title: "Cleveland Fed Inflation Expectations", actual: "", forecast: "", previous: "3.1%" },
    EconomicEvent { date: "2026-05-12", time: "10:00pm", currency: "JPY", impact: Impact::Low, title: "Economy Watchers Sentiment", actual: "", forecast: "", previous: "42.2" },
    EconomicEvent { date: "2026-05-12", time: "10:01am", currency: "USD", impact: Impact::Low, title: "10-y Bond Auction", actual: "", forecast: "", previous: "4.28|2.4" },
    EconomicEvent { date: "2026-05-12", time: "11:00am", currency: "USD", impact: Impact::Low, title: "Federal Budget Balance", actual: "", forecast: "", previous: "-164.1B" },
    EconomicEvent { date: "2026-05-12", time: "11:45pm", currency: "EUR", impact: Impact::Low, title: "French Final CPI m/m", actual: "", forecast: "", previous: "1.0%" },
    EconomicEvent { date: "2026-05-12", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Italian Industrial Production m/m", actual: "", forecast: "", previous: "0.1%" },
    EconomicEvent { date: "2026-05-12", time: "1:30pm", currency: "USD", impact: Impact::Low, title: "API Weekly Statistical Bulletin", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-12", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "German ZEW Economic Sentiment", actual: "", forecast: "", previous: "-17.2" },
    EconomicEvent { date: "2026-05-12", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "ZEW Economic Sentiment", actual: "", forecast: "", previous: "-20.4" },
    EconomicEvent { date: "2026-05-12", time: "2:30am", currency: "AUD", impact: Impact::Low, title: "Annual Budget Release", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-12", time: "3:00am", currency: "USD", impact: Impact::Low, title: "NFIB Small Business Index", actual: "", forecast: "", previous: "95.8" },
    EconomicEvent { date: "2026-05-12", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Bank Lending y/y", actual: "", forecast: "", previous: "4.8%" },
    EconomicEvent { date: "2026-05-12", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Current Account", actual: "", forecast: "", previous: "2.71T" },
    EconomicEvent { date: "2026-05-12", time: "5:15am", currency: "USD", impact: Impact::Low, title: "ADP Weekly Employment Change", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-12", time: "5:30am", currency: "USD", impact: Impact::High, title: "Core CPI m/m", actual: "", forecast: "", previous: "0.2%" },
    EconomicEvent { date: "2026-05-12", time: "5:30am", currency: "USD", impact: Impact::High, title: "CPI m/m", actual: "", forecast: "", previous: "0.9%" },
    EconomicEvent { date: "2026-05-12", time: "5:30am", currency: "USD", impact: Impact::High, title: "CPI y/y", actual: "", forecast: "", previous: "3.3%" },
    EconomicEvent { date: "2026-05-12", time: "6:30pm", currency: "AUD", impact: Impact::Medium, title: "Wage Price Index q/q", actual: "", forecast: "", previous: "0.8%" },
    EconomicEvent { date: "2026-05-12", time: "7:30am", currency: "AUD", impact: Impact::Low, title: "CB Leading Index m/m", actual: "", forecast: "", previous: "1.1%" },
    EconomicEvent { date: "2026-05-12", time: "8:00pm", currency: "NZD", impact: Impact::Low, title: "Inflation Expectations q/q", actual: "", forecast: "", previous: "2.37%" },
    EconomicEvent { date: "2026-05-12", time: "Tentative", currency: "CNY", impact: Impact::Low, title: "Foreign Direct Investment ytd/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "10:01am", currency: "USD", impact: Impact::Low, title: "30-y Bond Auction", actual: "", forecast: "", previous: "4.88|2.4" },
    EconomicEvent { date: "2026-05-13", time: "10:30am", currency: "CAD", impact: Impact::Low, title: "BOC Summary of Deliberations", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::High, title: "GDP m/m", actual: "", forecast: "", previous: "0.5%" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Medium, title: "Prelim GDP q/q", actual: "", forecast: "", previous: "0.1%" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Construction Output m/m", actual: "", forecast: "", previous: "1.0%" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Goods Trade Balance", actual: "", forecast: "", previous: "-18.8B" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Index of Services 3m/3m", actual: "", forecast: "", previous: "0.5%" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Industrial Production m/m", actual: "", forecast: "", previous: "0.5%" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Manufacturing Production m/m", actual: "", forecast: "", previous: "-0.1%" },
    EconomicEvent { date: "2026-05-13", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Prelim Business Investment q/q", actual: "", forecast: "", previous: "-2.5%" },
    EconomicEvent { date: "2026-05-13", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Flash Employment Change q/q", actual: "", forecast: "", previous: "0.2%" },
    EconomicEvent { date: "2026-05-13", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Flash GDP q/q", actual: "", forecast: "", previous: "0.3%" },
    EconomicEvent { date: "2026-05-13", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Industrial Production m/m", actual: "", forecast: "", previous: "0.4%" },
    EconomicEvent { date: "2026-05-13", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "Visitor Arrivals m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "4:01pm", currency: "GBP", impact: Impact::Low, title: "RICS House Price Balance", actual: "", forecast: "", previous: "-23%" },
    EconomicEvent { date: "2026-05-13", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "M2 Money Stock y/y", actual: "", forecast: "", previous: "2.0%" },
    EconomicEvent { date: "2026-05-13", time: "5:30am", currency: "USD", impact: Impact::High, title: "Core PPI m/m", actual: "", forecast: "", previous: "0.1%" },
    EconomicEvent { date: "2026-05-13", time: "5:30am", currency: "USD", impact: Impact::High, title: "PPI m/m", actual: "", forecast: "", previous: "0.5%" },
    EconomicEvent { date: "2026-05-13", time: "6:00pm", currency: "AUD", impact: Impact::Low, title: "MI Inflation Expectations", actual: "", forecast: "", previous: "5.9%" },
    EconomicEvent { date: "2026-05-13", time: "6:30am", currency: "GBP", impact: Impact::Low, title: "CB Leading Index m/m", actual: "", forecast: "", previous: "-0.1%" },
    EconomicEvent { date: "2026-05-13", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Crude Oil Inventories", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "8:35pm", currency: "JPY", impact: Impact::Low, title: "30-y Bond Auction", actual: "", forecast: "", previous: "3.70|3.1" },
    EconomicEvent { date: "2026-05-13", time: "All Day", currency: "CHF", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "All Day", currency: "EUR", impact: Impact::Holiday, title: "French Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "All Day", currency: "EUR", impact: Impact::Holiday, title: "German Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "Tentative", currency: "GBP", impact: Impact::Low, title: "10-y Bond Auction", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-13", time: "Tentative", currency: "EUR", impact: Impact::Low, title: "German 30-y Bond Auction", actual: "", forecast: "", previous: "3.58|1.4" },
    EconomicEvent { date: "2026-05-14", time: "11:00pm", currency: "JPY", impact: Impact::Low, title: "Prelim Machine Tool Orders y/y", actual: "", forecast: "", previous: "28.0%" },
    EconomicEvent { date: "2026-05-14", time: "3:30pm", currency: "NZD", impact: Impact::Low, title: "BusinessNZ Manufacturing Index", actual: "", forecast: "", previous: "53.2" },
    EconomicEvent { date: "2026-05-14", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "FPI m/m", actual: "", forecast: "", previous: "-0.6%" },
    EconomicEvent { date: "2026-05-14", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "PPI y/y", actual: "", forecast: "", previous: "2.6%" },
    EconomicEvent { date: "2026-05-14", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "Wholesale Sales m/m", actual: "", forecast: "", previous: "2.0%" },
    EconomicEvent { date: "2026-05-14", time: "5:30am", currency: "USD", impact: Impact::High, title: "Core Retail Sales m/m", actual: "", forecast: "", previous: "1.9%" },
    EconomicEvent { date: "2026-05-14", time: "5:30am", currency: "USD", impact: Impact::High, title: "Retail Sales m/m", actual: "", forecast: "", previous: "1.7%" },
    EconomicEvent { date: "2026-05-14", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Unemployment Claims", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-14", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Import Prices m/m", actual: "", forecast: "", previous: "0.8%" },
    EconomicEvent { date: "2026-05-14", time: "7:00am", currency: "USD", impact: Impact::Low, title: "Business Inventories m/m", actual: "", forecast: "", previous: "0.4%" },
    EconomicEvent { date: "2026-05-14", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Natural Gas Storage", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-14", time: "Tentative", currency: "CNY", impact: Impact::Low, title: "M2 Money Supply y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-14", time: "Tentative", currency: "CNY", impact: Impact::Low, title: "New Loans", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-14", time: "Tentative", currency: "USD", impact: Impact::Low, title: "Mortgage Delinquencies", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-14", time: "Tentative", currency: "USD", impact: Impact::Low, title: "FOMC Financial Stability Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-15", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "ECB Economic Bulletin", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-15", time: "5:15am", currency: "CAD", impact: Impact::Low, title: "Housing Starts", actual: "", forecast: "", previous: "236K" },
    EconomicEvent { date: "2026-05-15", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "Foreign Securities Purchases", actual: "", forecast: "", previous: "6.17B" },
    EconomicEvent { date: "2026-05-15", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "Manufacturing Sales m/m", actual: "", forecast: "", previous: "3.6%" },
    EconomicEvent { date: "2026-05-15", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Empire State Manufacturing Index", actual: "", forecast: "", previous: "11.0" },
    EconomicEvent { date: "2026-05-15", time: "6:15am", currency: "USD", impact: Impact::Low, title: "Capacity Utilization Rate", actual: "", forecast: "", previous: "75.7%" },
    EconomicEvent { date: "2026-05-15", time: "6:15am", currency: "USD", impact: Impact::Low, title: "Industrial Production m/m", actual: "", forecast: "", previous: "-0.5%" },
    EconomicEvent { date: "2026-05-15", time: "Tentative", currency: "USD", impact: Impact::Low, title: "Treasury Currency Report", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "3:30pm", currency: "NZD", impact: Impact::Low, title: "BusinessNZ Services Index", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "4:01pm", currency: "GBP", impact: Impact::Low, title: "Rightmove HPI m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "6:30pm", currency: "CNY", impact: Impact::Low, title: "New Home Prices m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "7:00pm", currency: "CNY", impact: Impact::Low, title: "Fixed Asset Investment ytd/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "7:00pm", currency: "CNY", impact: Impact::Low, title: "Industrial Production y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "7:00pm", currency: "CNY", impact: Impact::Low, title: "NBS Press Conference", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "7:00pm", currency: "CNY", impact: Impact::Low, title: "Retail Sales y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-17", time: "7:00pm", currency: "CNY", impact: Impact::Low, title: "Unemployment Rate", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "11:00pm", currency: "GBP", impact: Impact::High, title: "Claimant Count Change", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "11:00pm", currency: "GBP", impact: Impact::Medium, title: "Average Earnings Index 3m/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Unemployment Rate", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "18th-22nd", currency: "GBP", impact: Impact::Low, title: "CBI Industrial Order Expectations", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Italian Trade Balance", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "1:00pm", currency: "USD", impact: Impact::Low, title: "TIC Long-Term Purchases", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "EU Economic Forecasts", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "PPI Input q/q", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "PPI Output q/q", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Prelim GDP Price Index y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Prelim GDP q/q", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "6:30pm", currency: "AUD", impact: Impact::Low, title: "Monetary Policy Meeting Minutes", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "7:00am", currency: "USD", impact: Impact::Low, title: "NAHB Housing Market Index", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "9:30pm", currency: "JPY", impact: Impact::Low, title: "Revised Industrial Production m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "9:30pm", currency: "JPY", impact: Impact::Low, title: "Tertiary Industry Activity m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "All Day", currency: "CAD", impact: Impact::Holiday, title: "Bank Holiday", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-18", time: "Tentative", currency: "GBP", impact: Impact::Low, title: "30-y Bond Auction", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German PPI m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "11:00pm", currency: "GBP", impact: Impact::High, title: "CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Core CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "PPI Input m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "PPI Output m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "RPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "1:30pm", currency: "USD", impact: Impact::Low, title: "API Weekly Statistical Bulletin", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "20th-22nd", currency: "EUR", impact: Impact::Low, title: "German Final GDP q/q", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Trade Balance", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:15am", currency: "USD", impact: Impact::Low, title: "ADP Weekly Employment Change", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::High, title: "CPI m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::Medium, title: "Common CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::Medium, title: "Median CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::Medium, title: "Trimmed CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "Building Permits m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "Core CPI m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30am", currency: "CAD", impact: Impact::Low, title: "NHPI m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "5:30pm", currency: "AUD", impact: Impact::Low, title: "MI Leading Index m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "6:00pm", currency: "CNY", impact: Impact::Low, title: "1-y Loan Prime Rate", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "6:00pm", currency: "CNY", impact: Impact::Low, title: "5-y Loan Prime Rate", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "7:00am", currency: "USD", impact: Impact::Medium, title: "Pending Home Sales m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-19", time: "Tentative", currency: "NZD", impact: Impact::Low, title: "GDT Price Index", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "11:00am", currency: "USD", impact: Impact::High, title: "FOMC Meeting Minutes", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "1:30am", currency: "GBP", impact: Impact::Low, title: "HPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Final Core CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "2:00am", currency: "EUR", impact: Impact::Low, title: "Final CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "Trade Balance", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "4:00pm", currency: "AUD", impact: Impact::Low, title: "Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "4:00pm", currency: "AUD", impact: Impact::Low, title: "Flash Services PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Core Machinery Orders m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "4:50pm", currency: "JPY", impact: Impact::Low, title: "Trade Balance", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "5:30pm", currency: "JPY", impact: Impact::Low, title: "Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "6:30pm", currency: "AUD", impact: Impact::High, title: "Employment Change", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "6:30pm", currency: "AUD", impact: Impact::High, title: "Unemployment Rate", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Crude Oil Inventories", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "8:00pm", currency: "NZD", impact: Impact::Low, title: "Credit Card Spending y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-20", time: "Tentative", currency: "EUR", impact: Impact::Low, title: "German 10-y Bond Auction", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "11:00pm", currency: "EUR", impact: Impact::Low, title: "German GfK Consumer Climate", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "11:00pm", currency: "GBP", impact: Impact::Medium, title: "Retail Sales m/m", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "11:00pm", currency: "GBP", impact: Impact::Low, title: "Public Sector Net Borrowing", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "12:15am", currency: "EUR", impact: Impact::Medium, title: "French Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "12:15am", currency: "EUR", impact: Impact::Medium, title: "French Flash Services PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "12:30am", currency: "EUR", impact: Impact::Medium, title: "German Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "12:30am", currency: "EUR", impact: Impact::Medium, title: "German Flash Services PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Current Account", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "1:00am", currency: "EUR", impact: Impact::Low, title: "Flash Services PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "1:30am", currency: "GBP", impact: Impact::High, title: "Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "1:30am", currency: "GBP", impact: Impact::High, title: "Flash Services PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "Core Retail Sales q/q", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "3:45pm", currency: "NZD", impact: Impact::Low, title: "Retail Sales q/q", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "4:01pm", currency: "GBP", impact: Impact::Low, title: "GfK Consumer Confidence", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "4:30pm", currency: "JPY", impact: Impact::Low, title: "National Core CPI y/y", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Philly Fed Manufacturing Index", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "5:30am", currency: "USD", impact: Impact::Medium, title: "Unemployment Claims", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Building Permits", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "5:30am", currency: "USD", impact: Impact::Low, title: "Housing Starts", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "6:45am", currency: "USD", impact: Impact::Medium, title: "Flash Manufacturing PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "6:45am", currency: "USD", impact: Impact::Medium, title: "Flash Services PMI", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "7:00am", currency: "EUR", impact: Impact::Low, title: "Consumer Confidence", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "7:30am", currency: "USD", impact: Impact::Low, title: "Natural Gas Storage", actual: "", forecast: "", previous: "" },
    EconomicEvent { date: "2026-05-21", time: "Tentative", currency: "GBP", impact: Impact::Low, title: "10-y Bond Auction", actual: "", forecast: "", previous: "" },
];
